### ISSUE TITLE
MUI createTheme_default is not a function

### ISSUE THREAD

**Issue by gabrielbuii** [viclafouch/mui-color-input#15]
Hi!

Thank you for the amazing package, really appreciate it!:) However, I encountered an issue after installing it.

**Describe the bug**
`Uncaught TypeError: createTheme_default is not a function at Box.js:6:22`

**Screenshots**
![Screenshot from 2023-05-17 15-50-25](https://github.com/viclafouch/mui-color-input/assets/133883077/b71185f3-1e7c-4813-ad36-62ad76bc1ead)

![box](https://github.com/viclafouch/mui-color-input/assets/133883077/9878c61b-d163-4cfb-a2d1-ed5ac5457791)

**Should fix it:**
Following this [stackoverflow post](https://stackoverflow.com/questions/74542488/react-material-ui-createtheme-default-is-not-a-function), if we replace the 
	`import Box from '@mui/material/Box';` 
to 
	`import { Box } from '@mui/material';`
in	
	`ColorPopoverBody.tsx`

then it should fix it.

**Desktop:**
 - OS: Ubuntu 22.04
 - Browser: Chrome
 - Version: Version 113.0.5672.92 (Official Build) (64-bit) 

**Additional context**
Versions of MUI packages we use in a project:
```
 "@emotion/cache": "^11.11.0",
 "@emotion/react": "^11.11.0",
 "@emotion/styled": "^11.11.0",
 "@mui/icons-material": "^5.11.16",
 "@mui/lab": "^5.0.0-alpha.129",
 "@mui/material": "^5.13.1",
 "@mui/x-date-pickers": "^6.4.0",
```

**Comment by viclafouch** [comment]
hey @gabrielbuii !

Humm don't think that the real issue here..  In a sandbox with the last versions of all package, it's still working for me :/

**Comment by gabrielbuii** [comment]
@viclafouch You are right, it was a Vite issue. Sorry for that. I will close both the issue and the pr.
