### ISSUE TITLE
Remove shadow on color's button

### ISSUE THREAD

**Issue by vbo75** [viclafouch/mui-color-input#2]
Hi,
Is it possible to remove shadow behind color's button ?

**Comment by viclafouch** [comment]
Hello ! 

Use can do it by using the given classNames : https://viclafouch.github.io/mui-color-input/docs/css/

**Comment by vbo75** [comment]
Thanks 👍 

Here's sample tested 

```
const CustomColorInput = styled(MuiColorInput)({
   "& .MuiColorInput-Button": {
       boxShadow: 'none',
   },
});
```
