### ISSUE TITLE
JEST - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by radelcom** [viclafouch/mui-color-input#22]
**Describe the bug**
Struggling to get correct transformation of ES to work on unit testings. Tried adding `babel` to deal with transformation but still not able to get it right for some reason.

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { jsx as c, jsxs as lt, Fragment as Mt } from "react/jsx-runtime";

    SyntaxError: Cannot use import statement outside a module
```

Tried:
- adding `babel.config.js`
```
module.exports = {
  presets: ['@babel/preset-env'],
  plugins: ['@babel/plugin-transform-modules-commonjs'],
};
```
- update `jest.config.js`
```
transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
    '^.+\\.(js|jsx)$': 'babel-jest',
  },
```

Any help would be greatly appreciated!

**Comment by viclafouch** [comment]
Hello !

Maybe check this : https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/

Hope it will help !

**Comment by Matt-Butler** [comment]
Just curious, has anyone has gotten this to work?

**Comment by antal-bukos** [comment]
I worked around it by adding it to `transformIgnorePatterns` in `jest.config.js`:
```
transformIgnorePatterns: ['node_modules/(?!mui-color-input)']
```
