### ISSUE TITLE
Automatic Text Field Focus on Popover Close: A Mobile Usability Issue

### ISSUE THREAD

**Issue by stefmabo** [viclafouch/mui-color-input#25]
Describe the bug
When closing a popover on the website, the text field is automatically focused. This behavior is particularly problematic on mobile devices, creating a poor user experience.

To Reproduce

Go to the relevant page with the popover.
Click on the popover to open it.
Close the popover by clicking outside this popover.
Notice that the text field gets automatically focused, causing the mobile device's keyboard to pop up.
Expected behavior
The expected behavior is that after closing the popover, no automatic focus should be applied if we send this instruction.

Screenshots
If applicable, screenshots to demonstrate the issue would be helpful.

Desktop (please complete the following information):

OS: [e.g., Windows, macOS]
Browser [e.g., Chrome, Firefox]
Version [e.g., 95]
Smartphone (please complete the following information):

Device: [e.g., Samsung Galaxy S10]
OS: [e.g., Android 10]
Browser [e.g., Google Chrome, Firefox]
Version [e.g., 87]
Additional context
Further details on specific conditions under which this behavior is observed, or any related observations that might assist in diagnosing and fixing the bug.

**Comment by stefmabo** [comment]
I already have the code, but I don't have permission to upload the branch.

**Comment by suiboli314** [comment]
> I already have the code, but I don't have permission to upload the branch.

Great to hear you've got the code ready! Would a pull request be the next step?

By the way, I've developed a utility tool using this module. It addresses the issue of autofocus after closing popover modals, which I believe is crucial for both user experience and accessibility, particularly on mobile devices. Feel free to take a look at it here: [link](https://suiboli314.vercel.app/colorProximity).

**Comment by viclafouch** [comment]
> I already have the code, but I don't have permission to upload the branch.

Hello ! 

Feel free to open a PR, in the meantime, I close this issue.
