### ISSUE TITLE
2.0.1 doesn't work on NextJS 14.0.4

### ISSUE THREAD

**Issue by pcreehan** [viclafouch/mui-color-input#28]
**Describe the bug**
When using mui-color-input on a production built web application using NextJs 14.0.4, the color preview thumbnail is always the default checker and the color set is always #000000.
|NextJS Version|MUI-Color-Input version|Works?|
|---|----|----|
|14.0.3|2.0.0| ✅ |
|14.0.3|2.0.1| ✅ |
|14.0.4|2.0.0| ✅ |
|14.0.4|2.0.1| ❌ |

dev builds work (`next dev`), but production builds (`next build && next start`) do not.

**To Reproduce**
[CodeSandbox repro](https://codesandbox.io/p/devbox/mui-color-repro-csg4ql?file=%2Fpackage.json&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr84cxao0007356a492ulnkh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr84cxao0002356a5j1wgi6u%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr84cxao0004356af09mqz5o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr84cxao0006356agwp5dgid%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr84cxao0002356a5j1wgi6u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr84cxan0001356az865bhmc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clr84trqi0002356a3h8tf5az%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clr84cxao0002356a5j1wgi6u%2522%252C%2522activeTabId%2522%253A%2522clr84trqi0002356a3h8tf5az%2522%257D%252C%2522clr84cxao0006356agwp5dgid%2522%253A%257B%2522id%2522%253A%2522clr84cxao0006356agwp5dgid%2522%252C%2522activeTabId%2522%253A%2522clr851ery01ir356a28kzb1d0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522VIRTUAL_MACHINE%2522%252C%2522id%2522%253A%2522clr84ug1z008v356alij11vud%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr8501o0018z356arccqfufc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clr851ery01ir356a28kzb1d0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clr84cxao0004356af09mqz5o%2522%253A%257B%2522id%2522%253A%2522clr84cxao0004356af09mqz5o%2522%252C%2522activeTabId%2522%253A%2522clr851bqp01gi356as2wmjkif%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clr84vr8b00mt356adrixtx2l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522clr84xqjr00tz356a9snh8f8g%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr84xqfl003eeege87pa45bj%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clr84zy7e017d356a11pgk6e1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clr851bqp01gi356as2wmjkif%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. Open the sandbox above
2. Interact with the mui-color-input control on the page.
3. Note that choosing a color doesn't close the selector and clicking away sets the color to #000000

**Expected behavior**
Clicking the color selector should fire the onChange event with the new color selected.

**Screenshots**
<img width="150" alt="image" src="https://github.com/viclafouch/mui-color-input/assets/8560828/03bb1712-02f7-4a7d-a470-d59b3c76d549">
<img width="197" alt="image" src="https://github.com/viclafouch/mui-color-input/assets/8560828/8cd00102-fd9e-48e7-8d58-4cee33f4c7e2">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Brave
 - Version 1.61.114 (chromium 120)

**Additional context**

**Comment by fatgy** [comment]
I had this issue and temporary fix by use "@ctrl/tinycolor": "^3.0.0".

Look like bug "@ctrl/tinycolor": "^4.0.2" compute wrong value.

**Comment by viclafouch** [comment]
Hummm I fixed just by install the missing packages :)

https://codesandbox.io/p/devbox/mui-color-repro-forked-rhz5vq
