### ISSUE TITLE
onPopupClosed

### ISSUE THREAD

**Issue by alinco8** [viclafouch/mui-color-input#32]
**Is your feature request related to a problem? Please describe.**

No way to get the value after the selection is done.

**Describe the solution you'd like**
**Please describe your desired solution clearly and concisely.**

Add onPopupClosed to be called when the popup is closed.
or onChangeComplete

**Describe alternatives you've considered**

None

**Additional context**

**Comment by JaitenThomas** [comment]
+1 please add.

**Comment by bbyuck** [comment]
I solved this issue with PopoverProps.

here is example.

`<MuiColorInput 
  PopoverProps={{
    onClose: () => { /* what you want to do */ }
  }}
/>`

I think if reference document contain this use case, this library would be used more easily!
