### ISSUE TITLE
Support MUI 6

### ISSUE THREAD

**Issue by GITSKayDomrose** [viclafouch/mui-color-input#40]
**Describe the bug**
Today they release MUI 6.
https://mui.com/blog/material-ui-v6-is-out/

It seems to be only new CSS-related features without any breaking changes.  

This package doesn't work with this update because MUI peer dependency is pinned to MUI 5.

**To Reproduce**
Try upgrade to `"@mui/material": "6.0.0"`.

```
npm error Found: @mui/material@6.0.0
npm error node_modules/@mui/material
npm error   @mui/material@"6.0.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @mui/material@"^5.0.0" from mui-color-input@3.0.0
npm error node_modules/mui-color-input
npm error   mui-color-input@"3.0.0" from the root project
```

**Expected behavior**
Support MUI 6

**Comment by viclafouch** [comment]
And if you force the install with `npm i --force`, it works well ? (Just to know if anything breaks)

**Comment by GITSKayDomrose** [comment]
> And if you force the install with `npm i --force`, it works well ? (Just to know if anything breaks)

It works
