### ISSUE TITLE
Previously Selected Colors

### ISSUE THREAD

**Issue by Kreachers** [viclafouch/mui-color-input#45]
**Is your feature request related to a problem? Please describe.**
It's frustrating trying to select the same color without knowing the exact color string. 

**Describe the solution you'd like**
I would like the popup to display the last 10 colors selected or maybe a favorites list so the user can choose what colors to select from.

**Describe alternatives you've considered**
I've tried handling this outside of this library but it don't look as good as if the library handled it in the popup.

**Additional context**
Something kind of like the bottom of this picker. Either stored in a cookie, session storage or local storage and saved when clicking off of the color picker to prevent it from being flooded by very similar colors. Another option is to have colors be passed in through a prop so the storage management could be handled outside of this library.

<img width="412" alt="Screenshot 2024-10-08 at 15 02 26" src="https://github.com/user-attachments/assets/565a0bb4-a417-48f2-aa38-004872d4d255">

**Comment by viclafouch** [comment]
Hello @Kreachers 

Thank you for your feature request ! 

After careful consideration, I have decided not to implement this feature directly into the library. The request for displaying a history of the last 10 selected colors or a favorites list is very specific and would add complexity to the library that may not be relevant for most users. I appreciate your understanding, and I'm happy to offer guidance on how to integrate this functionality externally if needed.
