### ISSUE TITLE
Please export ColorButton component

### ISSUE THREAD

**Issue by ianroberts** [viclafouch/mui-color-input#50]
`MuiColorInput` offers a prop `Adornment` which allows you to replace the `ColorButton` component, however the `ColorButton` component itself is not one of the module's exports, making the `Adornment` prop of limited use.  If `ColorButton` were exported then it would be possible to make, for example, a component that wraps a standard `ColorButton` in a `Tooltip`, spreading all its props to the child, or use `styled(ColorButton)(...)` to apply style customisations.  Without the export, the only thing that you can override the `Adornment` with is a completely custom component that happens to use the same props.

Hopefully this should only be a matter of adding an `export { ColorButton as MuiColorButton }` or similar to `index.tsx`.

**Comment by viclafouch** [comment]
Hello !

This has been added in v5.

See https://github.com/viclafouch/mui-color-input/releases/tag/v5.0.0
