### ISSUE TITLE
Allow for undefined instead of fallback color value

### ISSUE THREAD

**Issue by korneSt** [viclafouch/mui-color-input#8]
Hi,
Is there a possibility to not set any value for the input? 

Currently when I set initial value as empty string, and click later on the field it sets color to the fallbackValue. However I don't want that behavior because user don't always want to set a color. 

Is there a way to set the value to null or undefined instead of always setting some color?

**Comment by viclafouch** [comment]
Hello @korneSt !

Thanks a lot!

This issue has been fixed in https://github.com/viclafouch/mui-color-input/releases/tag/v1.0.4

Have a good holiday 😋
